version: '3.8'
services:
  crawler_app:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    depends_on:
      - crawler_db
    tty: true
  crawler_db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
volumes:
  postgres_data: